apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  cassandra-env.sh: |
    # Optimize JVM settings for Kubernetes on ARM64
    
    # Set JVM options for ARM64 architecture
    JVM_OPTS="$JVM_OPTS -XX:+UseG1GC"
    JVM_OPTS="$JVM_OPTS -XX:+ParallelRefProcEnabled"
    JVM_OPTS="$JVM_OPTS -XX:+UnlockExperimentalVMOptions"
    JVM_OPTS="$JVM_OPTS -XX:+DisableExplicitGC"
    JVM_OPTS="$JVM_OPTS -XX:MaxGCPauseMillis=200"
    
    # Read ahead optimization for ARM64
    if [ -e /sys/block/sda/queue/read_ahead_kb ]; then
      echo 8 > /sys/block/sda/queue/read_ahead_kb
    fi
    
    # Set optimal garbage collection settings
    JVM_OPTS="$JVM_OPTS -XX:InitiatingHeapOccupancyPercent=70"
    JVM_OPTS="$JVM_OPTS -XX:+UseCompressedOops"
    
    # Network and thread settings
    CASSANDRA_BROADCAST_ADDRESS=${POD_IP}
    CASSANDRA_LISTEN_ADDRESS=${POD_IP}
    CASSANDRA_RPC_ADDRESS=${POD_IP}
    CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
