apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  ports:
  - port: 9042
    targetPort: 9042
    name: cql
  - port: 7000
    targetPort: 7000
    name: intra-node
  - port: 7001
    targetPort: 7001
    name: tls-intra-node
  - port: 7199
    targetPort: 7199
    name: jmx
  selector:
    app: cassandra
